---

- name: Install Redis
  apt: name={{ item }} state=installed state=present
  with_items:
    - redis-server

- name: Start and enable Redis
  service: name=redis-server enabled=yes state=started
